apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: staff-service-svc
spec:
  hosts:
  - staff-service
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: staff-service

