apiVersion: v1
kind: Service
metadata:
  name: fleetman-staff-service
  labels:
    app: staff-service
spec:
  selector:
    app: staff-service
  ports:
    - name: http
      port: 8080
  type: ClusterIP
